# -*- coding: utf-8 -*-
"""Export the knowledge base for the browser build.

The browser build must not re-derive anything it can be handed.  Pattern keys
are collapsed here, by the same Python text layer the server uses, so the only
logic the JavaScript has to reproduce is collapsing the *query* -- and
eval/verify_web_port.js checks that it does.

Run:  python -m agrichat.export_web
"""

from __future__ import annotations

import json
import os

from . import kb
from .engine import CROP_ALIASES, AgriEngine, _flat
from .nepali_text import keys

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "web", "kb-bundle.js")


def build() -> dict:
    entries = kb.load()
    out_entries = []
    for entry in entries:
        pattern_keys = []
        for pattern in entry.patterns:
            k = keys(pattern)
            pattern_keys.append([_flat(k["tight"]), _flat(k["loose"]), k["stems"]])
        out_entries.append({
            "id": entry.id,
            "domain": entry.domain,
            "crops": entry.crops,
            "label": entry.patterns[0],
            "answer": entry.answer,
            "followups": entry.followups,
            "sources": entry.sources,
            "keys": pattern_keys,
        })

    testset_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "eval", "testset.json")
    with open(testset_path, encoding="utf-8") as fh:
        cases = json.load(fh)["cases"]

    return {
        "entries": out_entries,
        # Shipped so the review page can run the evaluation in the browser
        # instead of asking the reviewer to trust a number in the README.
        "testset": cases,
        "cropAliases": {
            crop: sorted({_flat(keys(a)["loose"]) for a in aliases if keys(a)["loose"]})
            for crop, aliases in CROP_ALIASES.items()
        },
        "config": {
            "weights": AgriEngine.WEIGHTS,
            "minScore": AgriEngine.MIN_SCORE,
            "minMargin": AgriEngine.MIN_MARGIN,
            "cropBonus": AgriEngine.CROP_BONUS,
            "cropPenalty": AgriEngine.CROP_PENALTY,
        },
    }


def main() -> int:
    bundle = build()
    payload = json.dumps(bundle, ensure_ascii=False, separators=(",", ":"))
    # A plain global, not a fetch: this has to work from the repo server, from
    # a file:// page and from a published artifact without three code paths.
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("// Generated by `python -m agrichat.export_web` -- do not edit.\n")
        # Assigned to a global rather than fetched, so the same file works from
        # the repo server, a file:// page, a published artifact and node.
        fh.write("(function (g) { g.AGRI_KB = ")
        fh.write(payload)
        fh.write("; })(typeof self !== 'undefined' ? self : globalThis);\n")
    n_patterns = sum(len(e["keys"]) for e in bundle["entries"])
    print(f"wrote {OUT}")
    print(f"  {len(bundle['entries'])} entries, {n_patterns} patterns, "
          f"{len(bundle['testset'])} test cases, {len(payload) / 1024:.0f} KB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
